In [1]:
import numpy as np
# Numpy stands for NUMerical PYthon


In [2]:
# Assign [1,2,3] to "array1" by using funtion in "np" and "array"
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 shape:', array1.shape)

array1 type: <class 'numpy.ndarray'>
array1 shape: (3,)


In [3]:
# Let's build different shape of the np array to check the diffent dimension of data shape
array2 = np.array([[1,2,3],[2,3,4]])
array3 = np.array([[1,2,3]])

print('array2 type:', type(array2))
print('array2 type:', type(array3))
print('array2 sahpe:', array2.shape)
print('array3 sahpe:', array3.shape)

array2 type: <class 'numpy.ndarray'>
array2 type: <class 'numpy.ndarray'>
array2 sahpe: (2, 3)
array3 sahpe: (1, 3)


In [4]:
# To handle the data set, we need to care of the types of data.
# Class of "list1" is 'list' and 'list1' has integer
list1 = [1,2,3]
print(type(list1))

<class 'list'>


In [5]:
# Change the data class 'list' to int32
array4 = np.array(list1)
print(type(array4))
print(array1, array1.dtype)

<class 'numpy.ndarray'>
[1 2 3] int32


In [6]:
# "list2" has int and string types of data
# "list3" has int and float types of data 
# And change these lists to ndarray
list2 = [1,2,'test']
list3 = [1,2,3.0]
print(type(list2), type(list3))
array5 = np.array(list2)
array6 = np.array(list3)
print(type(array5), type(array6))
print(array5, array5.dtype,array6, array6.dtype)
print("array5 changed the data type to Unicode and array6 changed the data type to float")
print ("Unicode differentiates the data with '' and float shows you the decimal points")

<class 'list'> <class 'list'>
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
['1' '2' 'test'] <U11 [1. 2. 3.] float64
array5 changed the data type to Unicode and array6 changed the data type to float
Unicode differentiates the data with '' and float shows you the decimal points


In [7]:
# In the machine learning world, they require to open a whole data set and do ML, so we need to save a memory by changing the types of the data set
# For example, float64 to int 
# This code will change data type int to float64 and change it back again
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [8]:
# Using arange fuction, we can have a series of numbers; 0 to 9 and it is integer type with 1D.
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [9]:
# zeros fills the data with 0 and we designate the data type and dimension.
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

# ones fills the data with 1 and if we don't specify the data type goes with a default, float64
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [10]:
# reshape function change the dimension of the data set
# (row, column)
array7 = np.arange(10)
print('array7:\n', array7)
array8 = array7.reshape(2,5)
print('array8:\n', array8)
array9 = array7.reshape(5,2)
print('array9:\n', array9)
# With 'array7', we couldn't make (4,3)

array7:
 [0 1 2 3 4 5 6 7 8 9]
array8:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array9:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [11]:
# If we apply -1 for row or column, it automatically match with a specified number, column or row.
array10 = array7.reshape(-1, 5)
array11 = array7.reshape(5, -1)
print(array10)
print(array11)
# However, if we set 4 for row or column, we couldn't get the result becuase we can have integer with 4 in 10.

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [12]:
array12 = np.arange(8)
array3d = array12.reshape(2,2,2)
print('array3d:\n', array3d)
# tolist function change the data type to 'list' and we use this to catch the differences easily.
print('array3d:\n', array3d.tolist())

# 3D to 2D
array13 = array3d.reshape(-1,1)
print('array13:\n', array13.tolist())
print('array13 shape:', array13.shape)

# 1D to 2D
array13 = array12.reshape(-1, 1)
print('array13:\n', array13.tolist())
print('array13 shape:', array13.shape)

array3d:
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array13:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array13 shape: (8, 1)
array13:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array13 shape: (8, 1)


In [13]:
# From here, we are going to check the indexing
array14 = np.arange(start=1, stop=10)
print('array14:', array14)

array14: [1 2 3 4 5 6 7 8 9]


In [15]:
# Index starts from '0' and 2 means the third one.
value = array14[2]
print('value:', value)
print(type(value))

value: 3
<class 'numpy.int32'>


In [16]:
# we can call the data from the last using '-'
print('the last:', array14[-1], 'the second from the last:', array14[-2])

the last: 9 the second from the last: 8


In [17]:
# With a single inedx, we can change the data.
array14[0] = 9
array14[8] = 0
print('Revised array14:', array14)

Revised array14: [9 2 3 4 5 6 7 8 0]


In [20]:
# Note! Specifically, in ndarray, we don't say row and column, but we say axis0 and axis1
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('row = 0, col = 0 is ', array2d[0, 0])
print('row = 0, col = 1 is ', array2d[0, 1] )
print('row = 1, col = 0 is ', array2d[1, 0])
print('row = 2, col = 2 is ', array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
row = 0, col = 0 is  1
row = 0, col = 1 is  2
row = 1, col = 0 is  4
row = 2, col = 2 is  9


In [26]:
# We can apply different export ways. Here we are going to do Slicing.
array15 = array14[0:3]
print(array14)
print(array15, type(array15))

array16 = array14[:3]
array17 = array14[3:]
array18 = array14[:]
print(array16)
print(array17)
print(array18)

[9 2 3 4 5 6 7 8 0]
[9 2 3] <class 'numpy.ndarray'>
[9 2 3]
[4 5 6 7 8 0]
[9 2 3 4 5 6 7 8 0]


In [33]:
# Same data export, in 2D data set
print('array2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])


array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [37]:
# Without the following index, it returns the 1d data
print(array2d[0].shape, array2d[0])
print(array2d[1].shape, array2d[1])

(3,) [1 2 3]
(3,) [4 5 6]


In [41]:
# Here, we are going to do Fancy indexing.
print(array2d)

# this returns (0,2) and (1,2)
array3 = array2d[[0, 1], 2]

# this returns (0,0), (0,1) and (1,0), (1,1)
array4 = array2d[[0,1], 0:2]

# this returns (0, :), (1, :)
array5 = array2d[[0,1]]
print(array3.tolist())
print(array4.tolist())
print(array5.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3, 6]
[[1, 2], [4, 5]]
[[1, 2, 3], [4, 5, 6]]
