In [50]:
import numpy as np
# Numpy stands for NUMerical PYthon


In [51]:
# Assign [1,2,3] to "array1" by using funtion in "np" and "array"
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 shape:', array1.shape)

array1 type: <class 'numpy.ndarray'>
array1 shape: (3,)


In [52]:
# Let's build different shape of the np array to check the diffent dimension of data shape
array2 = np.array([[1,2,3],[2,3,4]])
array3 = np.array([[1,2,3]])

print('array2 type:', type(array2))
print('array2 type:', type(array3))
print('array2 sahpe:', array2.shape)
print('array3 sahpe:', array3.shape)

array2 type: <class 'numpy.ndarray'>
array2 type: <class 'numpy.ndarray'>
array2 sahpe: (2, 3)
array3 sahpe: (1, 3)


In [53]:
# To handle the data set, we need to care of the types of data.
# Class of "list1" is 'list' and 'list1' has integer
list1 = [1,2,3]
print(type(list1))

<class 'list'>


In [54]:
# Change the data class 'list' to int32
array4 = np.array(list1)
print(type(array4))
print(array1, array1.dtype)

<class 'numpy.ndarray'>
[1 2 3] int32


In [55]:
# "list2" has int and string types of data
# "list3" has int and float types of data 
# And change these lists to ndarray
list2 = [1,2,'test']
list3 = [1,2,3.0]
print(type(list2), type(list3))
array5 = np.array(list2)
array6 = np.array(list3)
print(type(array5), type(array6))
print(array5, array5.dtype,array6, array6.dtype)
print("array5 changed the data type to Unicode and array6 changed the data type to float")
print ("Unicode differentiates the data with '' and float shows you the decimal points")

<class 'list'> <class 'list'>
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
['1' '2' 'test'] <U11 [1. 2. 3.] float64
array5 changed the data type to Unicode and array6 changed the data type to float
Unicode differentiates the data with '' and float shows you the decimal points


In [56]:
# In the machine learning world, they require to open a whole data set and do ML, so we need to save a memory by changing the types of the data set
# For example, float64 to int 
# This code will change data type int to float64 and change it back again
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [57]:
# Using arange fuction, we can have a series of numbers; 0 to 9 and it is integer type with 1D.
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [58]:
# zeros fills the data with 0 and we designate the data type and dimension.
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

# ones fills the data with 1 and if we don't specify the data type goes with a default, float64
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [59]:
# reshape function change the dimension of the data set
# (row, column)
array7 = np.arange(10)
print('array7:\n', array7)
array8 = array7.reshape(2,5)
print('array8:\n', array8)
array9 = array7.reshape(5,2)
print('array9:\n', array9)
# With 'array7', we couldn't make (4,3)

array7:
 [0 1 2 3 4 5 6 7 8 9]
array8:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array9:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [60]:
# If we apply -1 for row or column, it automatically match with a specified number, column or row.
array10 = array7.reshape(-1, 5)
array11 = array7.reshape(5, -1)
print(array10)
print(array11)
# However, if we set 4 for row or column, we couldn't get the result becuase we can have integer with 4 in 10.

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [61]:
array12 = np.arange(8)
array3d = array12.reshape(2,2,2)
print('array3d:\n', array3d)
# tolist function change the data type to 'list' and we use this to catch the differences easily.
print('array3d:\n', array3d.tolist())

# 3D to 2D
array13 = array3d.reshape(-1,1)
print('array13:\n', array13.tolist())
print('array13 shape:', array13.shape)

# 1D to 2D
array13 = array12.reshape(-1, 1)
print('array13:\n', array13.tolist())
print('array13 shape:', array13.shape)

array3d:
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array13:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array13 shape: (8, 1)
array13:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array13 shape: (8, 1)


In [62]:
# From here, we are going to check the indexing
array14 = np.arange(start=1, stop=10)
print('array14:', array14)

array14: [1 2 3 4 5 6 7 8 9]


In [63]:
# Index starts from '0' and 2 means the third one.
value = array14[2]
print('value:', value)
print(type(value))

value: 3
<class 'numpy.int32'>


In [64]:
# we can call the data from the last using '-'
print('the last:', array14[-1], 'the second from the last:', array14[-2])

the last: 9 the second from the last: 8


In [65]:
# With a single inedx, we can change the data.
array14[0] = 9
array14[8] = 0
print('Revised array14:', array14)

Revised array14: [9 2 3 4 5 6 7 8 0]


In [66]:
# Note! Specifically, in ndarray, we don't say row and column, but we say axis0 and axis1
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('row = 0, col = 0 is ', array2d[0, 0])
print('row = 0, col = 1 is ', array2d[0, 1] )
print('row = 1, col = 0 is ', array2d[1, 0])
print('row = 2, col = 2 is ', array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
row = 0, col = 0 is  1
row = 0, col = 1 is  2
row = 1, col = 0 is  4
row = 2, col = 2 is  9


In [67]:
# We can apply different export ways. Here we are going to do Slicing.
array15 = array14[0:3]
print(array14)
print(array15, type(array15))

array16 = array14[:3]
array17 = array14[3:]
array18 = array14[:]
print(array16)
print(array17)
print(array18)

[9 2 3 4 5 6 7 8 0]
[9 2 3] <class 'numpy.ndarray'>
[9 2 3]
[4 5 6 7 8 0]
[9 2 3 4 5 6 7 8 0]


In [68]:
# Same data export, in 2D data set
print('array2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])


array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [69]:
# Without the following index, it returns the 1d data
print(array2d[0].shape, array2d[0])
print(array2d[1].shape, array2d[1])

(3,) [1 2 3]
(3,) [4 5 6]


In [70]:
# Here, we are going to do Fancy indexing.
print(array2d)

# this returns (0,2) and (1,2)
array3 = array2d[[0, 1], 2]

# this returns (0,0), (0,1) and (1,0), (1,1)
array4 = array2d[[0,1], 0:2]

# this returns (0, :), (1, :)
array5 = array2d[[0,1]]
print(array3.tolist())
print(array4.tolist())
print(array5.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3, 6]
[[1, 2], [4, 5]]
[[1, 2, 3], [4, 5, 6]]


In [71]:
# Boolean indexing is fancy index function by searching and sorting (filtering) at the same time.
array1d = np.arange(start=1, stop=10)
array19 = array1d[array1d > 5]
print(array1d, array19)

[1 2 3 4 5 6 7 8 9] [6 7 8 9]


In [72]:
print(array1d > 5)

[False False False False False  True  True  True  True]


In [73]:
# In this case, "boolean_indexes" has the boolean data and IF it merge with data from "array1d" for "array20", based on the boolean data, "array20" has >5 data.
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array20 = array1d[boolean_indexes]
print(boolean_indexes, array20)

[False False False False False  True  True  True  True] [6 7 8 9]


In [74]:
# Once you use the index to print "array21", 5 to 8 means the index position. So, 6 to 9 is corresponding to the index calling number.
indexes = np.array([5, 6, 7, 8])
array21 = array1d[indexes]
print(array21)

[6 7 8 9]


In [75]:
org_array = np.array([3, 1, 9, 5])
print(org_array)

[3 1 9 5]


In [76]:
# In a case of using "np.sort()"
sort_array1 = np.sort(org_array)
print(org_array, sort_array1)

[3 1 9 5] [1 3 5 9]


In [77]:
# In a case of using "ndarray.sort()"
sort_array2 = org_array.sort()
print(org_array, sort_array2)
# "ndarray.sort() does not return the number, but it sorts the numbers"

[1 3 5 9] None


In [78]:
# In case of sorting with descending order 
sort_array2_desc = np.sort(org_array)[::-1]
print(sort_array2_desc)

[9 5 3 1]


In [79]:
# Matirix axis selection and re-arranging
array2d = np.array([[8,12],
                    [7,1]])
# Set "axis=0" means a vertical axis which is for 8 and 7
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('re-arrange in Row direction:\n', sort_array2d_axis0)


re-arrange in Row direction:
 [[ 7  1]
 [ 8 12]]


In [80]:
# Set "axis=1" means a horizental axis which is for 8 and 12
sort_array2d_axis1 = np.sort(array2d, axis=1)
print('re-arrange in Column direction:\n', sort_array2d_axis1)

re-arrange in Column direction:
 [[ 8 12]
 [ 1  7]]


In [81]:
# what the index of matrix is the order of the number in the matrix
# In this work, 3 has 0, and 1 has 1 so on...
org_array = np.array([3, 1, 9, 5])
# rearrange all of components and store their index which is the value in the original set
sort_indices = np.argsort([org_array])
print(type(sort_indices))
print('Original index of the matrix when arrange the matrix:', sort_indices)

<class 'numpy.ndarray'>
Original index of the matrix when arrange the matrix: [[1 0 3 2]]


In [86]:
org_array2 = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array2)[::-1]
print(type(sort_indices_desc))
print("Original index of the matrix when arrange the matrix in descending order:", sort_indices_desc)

<class 'numpy.ndarray'>
Original index of the matrix when arrange the matrix in descending order: [2 3 0 1]


In [91]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('score_array index when it rearranged with ascending order:', sort_indices_asc)
print('pring the name from name array when it arranged with ascending order:', name_array[sort_indices_asc])

score_array index when it rearranged with ascending order: [0 2 4 1 3]
pring the name from name array when it arranged with ascending order: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [93]:
# Inner product, dot product, scalar product, projection product...
A = np.array([[1,2,3],
             [4,5,6]])
B= np.array([[7,8],
             [9,10],
             [11,12]])
# 1,2,3 * 7,9,11 for (0,0)
dot_product = np.dot(A,B)
print(dot_product)

[[ 58  64]
 [139 154]]


In [102]:
# Transpose
transpose_mat_A = np.transpose(A)
transpose_mat_B = np.transpose(B)
print(transpose_mat_A,"\n","\n", transpose_mat_B)

[[1 4]
 [2 5]
 [3 6]] 
 
 [[ 7  9 11]
 [ 8 10 12]]
